"""The 'axiom build' command."""

from __future__ import annotations

import time
from pathlib import Path
from typing import TYPE_CHECKING

import click
import structlog

from axiom.cache import AXIOM_VERSION, CacheStore
from axiom.codegen.generator import generate_code, generate_with_verification
from axiom.codegen.post_processor import (
    post_process,
    validate_fastapi_router,
    validate_function_exists,
)
from axiom.config import load_settings
from axiom.errors import AxiomError, SecurityError
from axiom.escape.protected_blocks import extract_protected_blocks, inject_protected_blocks
from axiom.security.provenance import ProvenanceLog, create_provenance_entry
from axiom.security.scanner import scan_spec_file
from axiom.spec import parse_spec_file
from axiom.spec.models import Spec
from axiom.spec.resolver import CycleError, get_build_order
from axiom.verify.harness import verify_code_string

if TYPE_CHECKING:
    from axiom.config.settings import Settings

logger = structlog.get_logger()

# Generated file header (without license)
GENERATED_HEADER = """# AXIOM GENERATED - DO NOT EDIT
# This file was generated by Axiom from: {spec_path}
# Spec: {spec_name} v{spec_version}
# To modify this code, edit the spec file and run 'axiom build'

"""

# Default license headers
DEFAULT_LICENSE_HEADERS: dict[str, str] = {
    "MIT": """# MIT License
# Copyright (c) {year} {author}
# See LICENSE file for details.
""",
    "Apache-2.0": """# Licensed under the Apache License, Version 2.0
# See LICENSE file or http://www.apache.org/licenses/LICENSE-2.0
""",
    "GPL-3.0": """# GNU General Public License v3.0
# See LICENSE file or https://www.gnu.org/licenses/gpl-3.0.html
""",
    "BSD-3-Clause": """# BSD 3-Clause License
# See LICENSE file for details.
""",
    "NONE": "",
}


def _build_header(spec: Spec, spec_path: Path, settings: Settings) -> str:
    """Build the header for generated code including license.

    Args:
        spec: The parsed spec.
        spec_path: Path to the spec file.
        settings: Axiom settings.

    Returns:
        Complete header string with license and generation info.
    """
    import datetime

    parts = []

    # Add license header if configured
    if settings.security.license_header:
        # Custom license header takes precedence
        parts.append(settings.security.license_header.rstrip())
        parts.append("")
    elif settings.security.license != "NONE":
        license_template = DEFAULT_LICENSE_HEADERS.get(settings.security.license)
        if license_template:
            license_text = license_template.format(
                year=datetime.datetime.now().year,
                author=settings.project.name,
            )
            parts.append(license_text.rstrip())
            parts.append("")

    # Add standard generated header
    generated = GENERATED_HEADER.format(
        spec_path=spec_path.name,
        spec_name=spec.metadata.name,
        spec_version=spec.metadata.version,
    )
    parts.append(generated.rstrip())
    parts.append("")

    return "\n".join(parts)


@click.command()
@click.argument("spec_path", type=click.Path(exists=True))
@click.option(
    "--output", "-o", type=click.Path(), help="Output file path (default: generated/<name>.py)"
)
@click.option("--model", "-m", help="Override model for generation")
@click.option("--verify/--no-verify", default=True, help="Verify after generation")
@click.option("--force", "-f", is_flag=True, help="Ignore cache and regenerate")
@click.option("--dry-run", is_flag=True, help="Show what would be regenerated without doing it")
@click.option("--local-only", is_flag=True, help="Never send data to LLM APIs; only use cache")
@click.pass_context
def build(
    ctx: click.Context,
    spec_path: str,
    output: str | None,
    model: str | None,
    verify: bool,
    force: bool,
    dry_run: bool,
    local_only: bool,
) -> None:
    """Generate Python code from an .axiom spec file or directory.

    When given a directory, resolves dependencies and builds all specs in order.
    Uses content-addressed caching to skip generation when specs haven't changed.

    \b
    Examples:
      axiom build specs/validate_email.axiom
      axiom build specs/user_crud/              # Build all specs in directory
      axiom build specs/my_spec.axiom --no-verify
      axiom build specs/my_spec.axiom -o src/my_module.py
      axiom build specs/my_spec.axiom --model claude-opus-4-20250514
      axiom build specs/my_spec.axiom --force   # Ignore cache, regenerate
      axiom build specs/my_spec.axiom --dry-run # Show what would happen
      axiom build specs/my_spec.axiom --local-only  # Only use cache, no API calls
    """
    path = Path(spec_path)
    verbose = ctx.obj.get("verbose", False)

    # CLI flag overrides settings
    effective_local_only = local_only or False

    try:
        settings = load_settings()

        # Settings can also enable local_only mode
        effective_local_only = effective_local_only or settings.security.local_only

        # Initialize cache store
        cache_store = None
        if settings.cache.enabled and not force:
            cache_store = CacheStore(settings.get_cache_dir())

        # Initialize provenance log if enabled
        provenance_log = None
        if settings.security.enable_provenance:
            provenance_log = ProvenanceLog(settings.get_provenance_log_path())

        if path.is_dir():
            # Build all specs in directory
            _build_directory(
                ctx,
                path,
                settings,
                model,
                verify,
                force,
                dry_run,
                verbose,
                cache_store,
                effective_local_only,
                provenance_log,
            )
        else:
            # Build single spec
            _build_single_spec(
                ctx,
                path,
                output,
                settings,
                model,
                verify,
                force,
                dry_run,
                verbose,
                cache_store,
                effective_local_only,
                provenance_log,
            )

    except SecurityError as e:
        raise click.ClickException(f"Security check failed: {e}") from None
    except CycleError as e:
        raise click.ClickException(str(e)) from None
    except AxiomError as e:
        raise click.ClickException(str(e)) from None
    except Exception as e:
        logger.exception("Unexpected error during build")
        raise click.ClickException(f"Build failed: {e}") from None


def _build_directory(
    ctx: click.Context,
    directory: Path,
    settings: Settings,
    model: str | None,
    verify: bool,
    force: bool,
    dry_run: bool,
    verbose: bool,
    cache_store: CacheStore | None,
    local_only: bool,
    provenance_log: ProvenanceLog | None,
) -> None:
    """Build all specs in a directory in dependency order.

    Args:
        ctx: Click context.
        directory: Path to the directory.
        settings: Axiom settings.
        model: Optional model override.
        verify: Whether to verify after generation.
        force: Whether to force regeneration.
        dry_run: Whether to only show what would be done.
        verbose: Whether to show verbose output.
        cache_store: Optional cache store for caching.
        local_only: Whether to prevent LLM API calls.
        provenance_log: Optional provenance log for tracking.
    """
    click.echo(f"Building specs in: {directory}")
    if dry_run:
        click.echo("(dry-run mode - no files will be written)")
    if local_only:
        click.echo("(local-only mode - no LLM API calls)")
    click.echo("")

    # Get specs in dependency order
    built_specs: dict[str, Path] = {}
    total = 0
    success = 0
    cache_hits = 0
    cache_misses = 0

    for name, spec, spec_path in get_build_order(directory):
        total += 1
        click.echo(f"[{total}] Building: {name}")

        # Scan for secrets first (if enabled)
        if settings.security.enable_secret_scan:
            secret_matches = scan_spec_file(spec_path)
            if secret_matches:
                click.echo(f"    ✗ {name}: Potential secrets detected")
                for match in secret_matches:
                    click.echo(f"      - Line {match.line_number}: {match.pattern_name}")
                raise SecurityError(
                    f"Potential secrets detected in {spec_path.name}",
                    file_path=str(spec_path),
                    secret_matches=secret_matches,
                )

        # Determine output path
        generated_dir = settings.get_generated_dir()
        generated_dir.mkdir(parents=True, exist_ok=True)
        output_path = generated_dir / f"{spec.metadata.name}.py"

        # Get the model to use
        effective_model = model or settings.get_model_for_target(spec.metadata.target)

        try:
            # Build the spec
            result_path, was_cached = _build_spec_with_deps(
                spec=spec,
                spec_path=spec_path,
                output_path=output_path,
                settings=settings,
                model=effective_model,
                verify=verify,
                force=force,
                dry_run=dry_run,
                verbose=verbose,
                built_specs=built_specs,
                cache_store=cache_store,
                local_only=local_only,
                provenance_log=provenance_log,
            )

            if result_path:
                built_specs[name] = result_path
                success += 1
                if was_cached:
                    cache_hits += 1
                    click.echo(f"    ✓ {name} (cache HIT)")
                else:
                    cache_misses += 1
                    click.echo(f"    ✓ {name} (generated)")
            else:
                click.echo(f"    - {name} (skipped, up to date)")
                built_specs[name] = output_path
                success += 1

        except SecurityError:
            raise  # Re-raise security errors
        except Exception as e:
            click.echo(f"    ✗ {name}: {e}")
            logger.debug("Build failed", spec=name, error=str(e))

    click.echo("")
    click.echo(f"Build complete: {success}/{total} specs")
    if cache_store:
        click.echo(f"Cache stats: {cache_hits} hits, {cache_misses} misses")


def _build_spec_with_deps(
    spec: Spec,
    spec_path: Path,
    output_path: Path,
    settings: Settings,
    model: str,
    verify: bool,
    force: bool,
    dry_run: bool,
    verbose: bool,
    built_specs: dict[str, Path],
    cache_store: CacheStore | None,
    local_only: bool,
    provenance_log: ProvenanceLog | None,
) -> tuple[Path | None, bool]:
    """Build a single spec with dependency information.

    Args:
        spec: The parsed spec.
        spec_path: Path to the spec file.
        output_path: Path for the generated file.
        settings: Axiom settings.
        model: The model to use for generation.
        verify: Whether to verify after generation.
        force: Whether to force regeneration.
        dry_run: Whether to only show what would be done.
        verbose: Whether to show verbose output.
        built_specs: Dict of already built spec names to their output paths.
        cache_store: Optional cache store for caching.
        local_only: Whether to prevent LLM API calls.
        provenance_log: Optional provenance log for tracking.

    Returns:
        Tuple of (path to generated file or None if skipped, whether result was from cache).
    """
    start_time = time.time()
    spec_content = spec_path.read_text()

    # Extract protected blocks from existing output if it exists
    protected_blocks = []
    if output_path.exists():
        existing_code = output_path.read_text()
        protected_blocks = extract_protected_blocks(existing_code)
        if protected_blocks:
            logger.debug(
                "Extracted protected blocks",
                count=len(protected_blocks),
                names=[b.name for b in protected_blocks if b.name],
            )

    # Check cache first (unless forcing)
    if cache_store and not force:
        cache_status = cache_store.lookup(spec, model, AXIOM_VERSION)

        if cache_status.hit and cache_status.entry:
            # Cache hit - use cached code
            if dry_run:
                click.echo("    Would use cached code (cache HIT)")
                return output_path, True

            code = cache_status.entry.code

            # Re-inject protected blocks
            if protected_blocks:
                code = inject_protected_blocks(code, protected_blocks)

            # Add dependency imports if needed
            if spec.has_dependencies():
                code = _add_dependency_imports(code, spec, built_specs)

            # Add header
            header = _build_header(spec, spec_path, settings)
            final_code = header + code

            # Write output
            output_path.parent.mkdir(parents=True, exist_ok=True)
            output_path.write_text(final_code, encoding="utf-8")

            # Log provenance
            if provenance_log:
                duration_ms = int((time.time() - start_time) * 1000)
                entry = create_provenance_entry(
                    spec_name=spec.spec_name,
                    spec_content=spec_content,
                    model=model,
                    action="cache_hit",
                    result="success",
                    axiom_version=AXIOM_VERSION,
                    duration_ms=duration_ms,
                )
                provenance_log.log(entry)

            return output_path, True

        elif cache_status.entry and cache_status.reason:
            # Cache stale - re-verify cached code before regenerating
            if "axiom version changed" in cache_status.reason:
                click.echo(f"    Cache STALE ({cache_status.reason}) - re-verifying...")

                # Log cache stale event
                if provenance_log:
                    entry = create_provenance_entry(
                        spec_name=spec.spec_name,
                        spec_content=spec_content,
                        model=model,
                        action="cache_stale",
                        result="success",
                        axiom_version=AXIOM_VERSION,
                    )
                    provenance_log.log(entry)

                if dry_run:
                    click.echo("    Would re-verify cached code")
                    return output_path, False

                # Try to verify cached code with current version
                cached_code = cache_status.entry.code
                success, failures = verify_code_string(spec, cached_code, settings)

                if success:
                    click.echo("    ✓ Cached code still passes verification. Keeping cache.")
                    # Update cache with new version
                    cache_store.put(spec, model, cached_code, AXIOM_VERSION)

                    # Re-inject protected blocks
                    if protected_blocks:
                        cached_code = inject_protected_blocks(cached_code, protected_blocks)

                    # Add dependency imports if needed
                    if spec.has_dependencies():
                        cached_code = _add_dependency_imports(cached_code, spec, built_specs)

                    # Add header
                    header = _build_header(spec, spec_path, settings)
                    final_code = header + cached_code

                    # Write output
                    output_path.parent.mkdir(parents=True, exist_ok=True)
                    output_path.write_text(final_code, encoding="utf-8")

                    return output_path, True
                else:
                    click.echo("    ✗ Cached code fails verification. Regenerating...")
                    # Fall through to regenerate
            else:
                click.echo(f"    Cache MISS ({cache_status.reason})")

                # Log cache miss
                if provenance_log:
                    entry = create_provenance_entry(
                        spec_name=spec.spec_name,
                        spec_content=spec_content,
                        model=model,
                        action="cache_miss",
                        result="success",
                        axiom_version=AXIOM_VERSION,
                    )
                    provenance_log.log(entry)

    if dry_run:
        click.echo("    Would generate new code")
        return output_path, False

    # Check local_only mode - cannot generate without API access
    if local_only:
        raise AxiomError(
            f"Cannot generate '{spec.spec_name}' in --local-only mode: "
            "not found in cache. Run without --local-only to generate."
        )

    # Generate code
    if verify:

        def verify_fn(code: str) -> tuple[bool, list[str]]:
            return verify_code_string(spec, code, settings)

        result = generate_with_verification(
            spec=spec,
            settings=settings,
            verify_fn=verify_fn,
            model_override=model,
        )
    else:
        result = generate_code(
            spec=spec,
            settings=settings,
            model_override=model,
        )

    # Post-process
    code = post_process(result.code, spec.spec_name)

    # Re-inject protected blocks
    if protected_blocks:
        code = inject_protected_blocks(code, protected_blocks)

    # Validate generated code structure
    if spec.is_fastapi:
        validate_fastapi_router(code, spec.function_name, spec.spec_name)
    else:
        validate_function_exists(code, spec.function_name, spec.spec_name)

    # Store in cache before adding header (header changes with spec path)
    if cache_store:
        cache_store.put(spec, model, code, AXIOM_VERSION)

    # Log provenance for generation
    if provenance_log:
        duration_ms = int((time.time() - start_time) * 1000)
        entry = create_provenance_entry(
            spec_name=spec.spec_name,
            spec_content=spec_content,
            model=model,
            action="generate",
            result="success",
            axiom_version=AXIOM_VERSION,
            duration_ms=duration_ms,
        )
        provenance_log.log(entry)

    # Add dependency imports if needed
    if spec.has_dependencies():
        code = _add_dependency_imports(code, spec, built_specs)

    # Add header
    header = _build_header(spec, spec_path, settings)
    final_code = header + code

    # Write output
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(final_code, encoding="utf-8")

    return output_path, False


def _add_dependency_imports(
    code: str,
    spec: Spec,
    built_specs: dict[str, Path],
) -> str:
    """Add import statements for spec dependencies.

    Only adds imports that don't already exist in the code.

    Args:
        code: The generated code.
        spec: The spec with dependencies.
        built_specs: Dict of built spec names to their output paths.

    Returns:
        Code with dependency imports added.
    """
    dep_names = spec.get_spec_dependencies()
    if not dep_names:
        return code

    # Build import lines, checking if they already exist
    import_lines = []
    for dep_name in dep_names:
        if dep_name in built_specs:
            import_stmt = f"from {dep_name} import {dep_name}"
            # Only add if not already present in code
            if import_stmt not in code:
                import_lines.append(import_stmt)

    if not import_lines:
        return code

    # Find where to insert imports (after existing imports)
    lines = code.split("\n")
    insert_idx = 0

    # Skip past any existing imports
    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith("import ") or stripped.startswith("from "):
            insert_idx = i + 1
        elif stripped and not stripped.startswith("#"):
            # Found first non-import, non-comment line
            if insert_idx == 0:
                insert_idx = i
            break

    # Insert dependency imports
    for imp in reversed(import_lines):
        lines.insert(insert_idx, imp)

    # Add blank line after imports if needed
    if insert_idx < len(lines) - 1 and lines[insert_idx + len(import_lines)].strip():
        lines.insert(insert_idx + len(import_lines), "")

    return "\n".join(lines)


def _build_single_spec(
    ctx: click.Context,
    spec_file: Path,
    output: str | None,
    settings: Settings,
    model: str | None,
    verify: bool,
    force: bool,
    dry_run: bool,
    verbose: bool,
    cache_store: CacheStore | None,
    local_only: bool,
    provenance_log: ProvenanceLog | None,
) -> None:
    """Build a single spec file.

    Args:
        ctx: Click context.
        spec_file: Path to the spec file.
        output: Optional output path.
        settings: Axiom settings.
        model: Optional model override.
        verify: Whether to verify after generation.
        force: Whether to force regeneration.
        dry_run: Whether to only show what would be done.
        verbose: Whether to show verbose output.
        cache_store: Optional cache store for caching.
        local_only: Whether to prevent LLM API calls.
        provenance_log: Optional provenance log for tracking.
    """
    start_time = time.time()

    click.echo(f"\nBuilding: {spec_file.name}")
    click.echo("─" * 40)

    # Step 1: Scan for secrets (if enabled)
    if settings.security.enable_secret_scan:
        click.echo("  → Scanning for secrets...", nl=False)
        secret_matches = scan_spec_file(spec_file)
        if secret_matches:
            click.echo(" ✗")
            click.echo("    Potential secrets detected:")
            for match in secret_matches:
                click.echo(f"      Line {match.line_number}: {match.pattern_name}")
            raise SecurityError(
                f"Potential secrets detected in {spec_file.name}",
                file_path=str(spec_file),
                secret_matches=secret_matches,
            )
        click.echo(" ✓")

    # Step 2: Parse spec
    click.echo("  → Parsing spec...", nl=False)
    spec = parse_spec_file(spec_file)
    spec_content = spec_file.read_text()
    click.echo(" ✓")

    # Determine output path
    if output:
        output_path = Path(output)
    else:
        generated_dir = settings.get_generated_dir()
        generated_dir.mkdir(parents=True, exist_ok=True)
        output_path = generated_dir / f"{spec.metadata.name}.py"

    # Get the model to use
    effective_model = model or settings.get_model_for_target(spec.metadata.target)

    # Step 3: Extract protected blocks from existing output if it exists
    protected_blocks = []
    if output_path.exists():
        existing_code = output_path.read_text()
        protected_blocks = extract_protected_blocks(existing_code)
        if protected_blocks:
            click.echo(f"  → Found {len(protected_blocks)} protected block(s) to preserve")

    # Step 4: Check cache (unless forcing)
    if cache_store and not force:
        click.echo("  → Checking cache...", nl=False)
        cache_status = cache_store.lookup(spec, effective_model, AXIOM_VERSION)

        if cache_status.hit and cache_status.entry:
            # Cache hit - use cached code
            click.echo(" HIT")

            if dry_run:
                click.echo(f"  → Would write cached code to: {output_path}")
                return

            code = cache_status.entry.code

            # Re-inject protected blocks
            if protected_blocks:
                code = inject_protected_blocks(code, protected_blocks)

            # Add header
            header = _build_header(spec, spec_file, settings)
            final_code = header + code

            # Write output
            click.echo("  → Writing output...", nl=False)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            output_path.write_text(final_code, encoding="utf-8")
            click.echo(" ✓")

            duration_ms = int((time.time() - start_time) * 1000)
            click.echo(f"\n✓ Build complete ({duration_ms}ms) — {output_path}")

            # Log provenance
            if provenance_log:
                duration_ms = int((time.time() - start_time) * 1000)
                entry = create_provenance_entry(
                    spec_name=spec.spec_name,
                    spec_content=spec_content,
                    model=effective_model,
                    action="cache_hit",
                    result="success",
                    axiom_version=AXIOM_VERSION,
                    duration_ms=duration_ms,
                )
                provenance_log.log(entry)

            # Still verify if requested
            if verify:
                _verify_code(spec, final_code, settings, verbose)
            return

        elif cache_status.entry and cache_status.reason:
            # Cache stale - re-verify cached code before regenerating
            if "axiom version changed" in cache_status.reason:
                click.echo(f" STALE ({cache_status.reason})")
                click.echo("  → Re-verifying cached code...", nl=False)

                # Log cache stale event
                if provenance_log:
                    entry = create_provenance_entry(
                        spec_name=spec.spec_name,
                        spec_content=spec_content,
                        model=effective_model,
                        action="cache_stale",
                        result="success",
                        axiom_version=AXIOM_VERSION,
                    )
                    provenance_log.log(entry)

                if dry_run:
                    click.echo("")
                    click.echo("  → Would re-verify cached code and regenerate if needed")
                    return

                # Try to verify cached code with current version
                cached_code = cache_status.entry.code
                success, failures = verify_code_string(spec, cached_code, settings)

                if success:
                    click.echo(" ✓ (still valid)")
                    # Update cache with new version
                    cache_store.put(spec, effective_model, cached_code, AXIOM_VERSION)

                    # Re-inject protected blocks
                    if protected_blocks:
                        cached_code = inject_protected_blocks(cached_code, protected_blocks)

                    # Add header
                    header = _build_header(spec, spec_file, settings)
                    final_code = header + cached_code

                    # Write output
                    click.echo("  → Writing output...", nl=False)
                    output_path.parent.mkdir(parents=True, exist_ok=True)
                    output_path.write_text(final_code, encoding="utf-8")
                    click.echo(" ✓")

                    duration_ms = int((time.time() - start_time) * 1000)
                    click.echo(f"\n✓ Build complete ({duration_ms}ms) — {output_path}")
                    return
                else:
                    click.echo(" ✗ (needs regeneration)")
                    # Fall through to regenerate
            else:
                click.echo(f" MISS ({cache_status.reason})")

                # Log cache miss
                if provenance_log:
                    entry = create_provenance_entry(
                        spec_name=spec.spec_name,
                        spec_content=spec_content,
                        model=effective_model,
                        action="cache_miss",
                        result="success",
                        axiom_version=AXIOM_VERSION,
                    )
                    provenance_log.log(entry)
        else:
            click.echo(" MISS")

            # Log cache miss
            if provenance_log:
                entry = create_provenance_entry(
                    spec_name=spec.spec_name,
                    spec_content=spec_content,
                    model=effective_model,
                    action="cache_miss",
                    result="success",
                    axiom_version=AXIOM_VERSION,
                )
                provenance_log.log(entry)

    if dry_run:
        click.echo(f"  → Would generate new code for: {spec.spec_name}")
        click.echo(f"  → Would write to: {output_path}")
        return

    # Check local_only mode - cannot generate without API access
    if local_only:
        raise AxiomError(
            f"Cannot generate '{spec.spec_name}' in --local-only mode: "
            "not found in cache. Run without --local-only to generate."
        )

    # Step 5: Generate code
    click.echo(f"  → Generating code ({effective_model})...", nl=False)

    if verify:
        # Generate with verification in the loop
        def verify_fn(code: str) -> tuple[bool, list[str]]:
            return verify_code_string(spec, code, settings)

        result = generate_with_verification(
            spec=spec,
            settings=settings,
            verify_fn=verify_fn,
            model_override=model,
        )
    else:
        # Generate without verification
        result = generate_code(
            spec=spec,
            settings=settings,
            model_override=model,
        )
    click.echo(f" ✓ ({result.duration_ms}ms)")

    # Step 6: Post-process
    click.echo("  → Post-processing...", nl=False)
    code = post_process(result.code, spec.spec_name)
    click.echo(" ✓")

    # Re-inject protected blocks
    if protected_blocks:
        code = inject_protected_blocks(code, protected_blocks)

    # Validate generated code structure
    if spec.is_fastapi:
        validate_fastapi_router(code, spec.function_name, spec.spec_name)
    else:
        validate_function_exists(code, spec.function_name, spec.spec_name)

    # Step 7: Store in cache
    if cache_store:
        click.echo("  → Caching result...", nl=False)
        cache_store.put(spec, effective_model, code, AXIOM_VERSION)
        click.echo(" ✓")

    # Log provenance for generation
    if provenance_log:
        total_duration_ms = int((time.time() - start_time) * 1000)
        entry = create_provenance_entry(
            spec_name=spec.spec_name,
            spec_content=spec_content,
            model=effective_model,
            action="generate",
            result="success",
            axiom_version=AXIOM_VERSION,
            duration_ms=total_duration_ms,
        )
        provenance_log.log(entry)

    # Add header
    header = _build_header(spec, spec_file, settings)
    final_code = header + code

    # Step 8: Write output
    click.echo("  → Writing output...", nl=False)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(final_code, encoding="utf-8")
    click.echo(" ✓")

    # Summary
    total_duration_ms = int((time.time() - start_time) * 1000)
    click.echo(f"\n✓ Build complete ({total_duration_ms}ms)")
    click.echo(f"  Output: {output_path}")
    if result.attempts > 1:
        click.echo(f"  Attempts: {result.attempts}")

    # Final verification if we didn't verify in the loop
    if verify and not hasattr(result, "_verified"):
        _verify_code(spec, final_code, settings, verbose)


def _verify_code(spec: Spec, code: str, settings: Settings, verbose: bool) -> None:
    """Run verification and display results.

    Args:
        spec: The parsed spec.
        code: The generated code.
        settings: Axiom settings.
        verbose: Whether to show verbose output.
    """
    from axiom.verify.harness import verify_spec
    from axiom.verify.reporter import print_result

    click.echo("")
    click.echo("Running verification...")
    result = verify_spec(spec, code, settings)
    print_result(result, verbose=verbose)

    if not result.success:
        raise click.ClickException("Verification failed")
